# Site settings
title: Building Blocks for HTTP APIs
email: erik.wilde@dret.net
description: > # this means to ignore newlines until "baseurl:"
  Use building blocks for your HTTP APIs;
  Design and build better HTTP APIs.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://webconcepts.info" # the base hostname & protocol for your site
twitter_username: dret
github_username:  dret

# Build settings
markdown: kramdown